config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'

  scope '(:locale)', :locale => /ru|uk/ do

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    # Faq
    get 'faq', to: 'faq#index', as: 'faq_index'
    get 'faq/:id', to: 'faq#show', as: 'faq_item'

    # System usage index and show pages
    get 'usage', to: 'publication#usage_index', as: 'usage_index'
    get 'usage/:id', to: 'publication#usage_show', as: 'usage_show'

    # News index and show pages
    get 'news', to: 'publication#news_index', as: 'news_index'
    get 'news/:id', to: 'publication#news_show', as: 'news_show'

    # Articles index and show pages
    get 'articles', to: 'publication#articles_index', as: 'articles_index'
    get 'articles/:id', to: 'publication#articles_show', as: 'articles_show'

    # Work out for products
    get 'equipments', to: 'product#index', as: 'product_index'
    get 'equipments/:product_type_id', to: 'product#by_type', as: 'product_by_type'
    get 'equipments/:product_type_id/:product_brand_id', to: 'product#by_brand', as: 'product_by_brand'
    get 'equipments/:product_type_id/:product_brand_id/:id', to: 'product#by_id', as: 'product_by_id'


    # Static pages
    get 'terms', to: 'page#terms', as: 'terms'
    get 'about-system', to: 'page#about_system', as: 'about_system'
    get 'about-us', to: 'page#about_us', as: 'about_us'
    get 'economy-effect', to: 'page#economy_effect', as: 'economy_effect'
    get 'page-not-found', to: 'page#error_404', as: 'page_not_found'
    get 'sitemap', to: 'page#sitemap', as: 'sitemap'

    get 'condition', to: 'page#condition', as: 'condition'

    get 'contact-us', to: 'contact#new', as: 'contact'
    get 'call-back', to: 'contact#feedback', as: 'feedback'
    #post 'contact-us', to: 'contact#create', as: 'contact'
    #resource :contacts, only: [:new, :create]
    #match 'contact-us' => 'contact#new', :as => 'contact', :via => :get
    #match 'contact-us' => 'contact#create', :as => 'contact', :via => :post

    # Root patch
    root 'page#index'

  end

end

app/views/partials/_bread.html.erb
<section id="breadcrumbs">
	<nav>
		<ul>
      <%= render_breadcrumbs :tag => :li, :separator => ' <li>/</li> ' %>
		</ul>
	</nav>



</section>

app/views/partials/_call_back.html.erb
<div id="call-back-wrapper">
  <form action="<%#= base_url %>" method="post" id="f_call_back" accept-charset="utf-8" autocomplete="on" onload="">
    <h2><%= t('system_elements.forms.call_back_header') %>:</h2>
    <div class="ll">
      <div class="field">
        <input data-validation="length" data-validation-error-msg="<%= t('system_elements.forms.validation_name') %>" data-validation-length="3-30" type="text" id="call-back-name" placeholder="Николай Воронин" aria-required="true"/>
        <label for="call-back-name" class="help-block"><%= t('system_elements.forms.label_name') %>:</label>
      </div>
      <div class="field">
        <input data-validation=" " data-validation-error-msg="<%= t('system_elements.forms.validation_phone') %>" data-validation-length="10" type="text" id="call-back-phone" placeholder="+38 (050) 417 07 28" aria-required="true"/>
        <label for="call-back-phone"><%= t('system_elements.forms.label_phone') %>:</label>
      </div>
      <div class="field">
        <input data-validation="email" data-validation-error-msg="<%= t('system_elements.forms.validation_email') %>" type="text" id="call-back-email" placeholder="voronin.nick@gmail.com" aria-required="true"/>
        <label for="call-back-email"><%= t('system_elements.forms.label_email') %>:</label>
      </div>
    </div>

    <div class="rr">
      <div class="field">
        <textarea data-validation="required" data-validation-error-msg="<%= t('system_elements.forms.validation_body') %>" name="call-back-body" id="call-back-body" cols="30" rows="10" placeholder="Введите ваш вопрос" aria-required="true"></textarea>
        <label for="call-back-body"><%= t('system_elements.forms.label_body') %>:</label>
      </div>
      <div class="field">
        <button type="submit" id="call-back-submit">Задать вопрос</button>
      </div>
    </div>
  </form>
</div>

app/views/partials/_form_mailer.html.erb
<section id="mailer">
  <div class="mailer-holder">
    <h2>Задать вопрос:</h2>
    <form class="ask-question clearfix" action="" method="post" id="ask-question-form">
      <div class="l">
        <div class="field">
          <input data-validation="length" data-validation-error-msg="<%= t('system_elements.forms.validation_name') %>" data-validation-length="3-30" type="text" id="firstname" placeholder="Николай Воронин"/>
          <label for="firstname">Ваше имя:</label>
        </div>
        <div class="field">
          <input data-validation="email" data-validation-error-msg="<%= t('system_elements.forms.validation_email') %>" type="text" id="email" placeholder="voronin.nick@gmail.com" />
          <label for="email">Ел. почта:</label>
        </div>
        <div class="field">
          <input data-validation="length" data-validation-error-msg="<%= t('system_elements.forms.validation_name') %>" data-validation-length="3-30" type="text" id="theme" placeholder="Введите тему вашего вопроса" />
          <label for="theme">Тема вопроса</label>
        </div>
        
      </div>
      <div class="r">
        <div class="field">
          <textarea data-validation="required" data-validation-error-msg="<%= t('system_elements.forms.validation_body') %>" name="body" id="body" cols="30" rows="10" placeholder="Введите ваш вопрос"></textarea>
          <label for="body">Суть вопроса</label>
        </div>
        <div class="field">
          <button type="submit" id="submit">Задать вопрос</button>
        </div>
      </div>
    </form>
  </div>
</section>

app/views/partials/_header_index.html.erb
<header id="indexpage">


  <div id="logo-index" class="clearfix">
    <div class="holder">
      <%= link_to_unless current_page?(controller: 'page', action: 'index') || current_page?('/'), image_tag('logo-index.png', :alt => ' '), root_path %>
    </div>
  </div>
	<nav id="main-navigation">
		<ul>
			<li id="logo">
				<%= link_to_unless current_page?(controller: 'page', action: 'index') || current_page?('/'), image_tag('logo-index.png', :alt => ' '), root_path %>
			</li>
			<li>
        <%= link_to about_system_path do %>
				<i>возможности</i>
				<b>системы</b>
        <% end %>
			</li>
			<li>
				<%= link_to usage_index_path do %>
					<i>области</i>
					<b>применения</b>
				<% end %>
			</li>
			<li id="eq-li">
        <%= link_to product_index_path, id: 'equipment_nav' do %>
				<i>необходимое</i>
				<b>оборудование</b>
        <% end %>
        <ol id="sub_nav_main">
          <li class="gps_li"> <i class="gps_m"></i> <%= link_to 'GPS трекеры', product_by_type_path(:product_type_id => 'gps-trekery') %><hr/></li>
          <li class="add_li"> <i class="add_m"></i> <%= link_to 'Дополнительное оборудование', product_by_type_path(:product_type_id => 'dopolnitelnoe-oborudovanie') %><hr/></li>
          <li class="controll_li"> <i class="controll_m"></i> <%= link_to 'Контроль топлива', product_by_type_path(:product_type_id => 'kontrol-topliva') %><hr/></li>
        </ol>
			</li>
			<li>
        <%= link_to economy_effect_path do %>
          <i>экономический</i>
          <b>эффект</b>
        <% end %>
			</li>
			<li>
        <%= link_to contact_path do %>
          <i>наши</i>
          <b>контакты</b>
        <% end %>
			</li>

		</ul>
	</nav>
  <%#= request.env.inspect %>
  <article class="slider">
    <div class="slider-controll">
      <div class="left prev"></div>
      <div class="right next"></div>
    </div>
    <ul>

      <script type="text/javascript" charset="utf-8">
        $(document).ready(function(no_click){
          $("#descr_no_click").click(function(no_click_e){
            no_click.preventDefault();
            no_click_e.preventDefault();
            return false;
          });
        });
      </script>
      <% @banners.each do |banner| %>
        <script type="text/javascript" charset="utf-8">
          $(document).ready(function(e){
            $(".slider-<%= banner.id %>").css("background", "url('<%= banner.avatar.url %>') no-repeat top center");

            $("#slider-<%= banner.id %>-click-action").click(function(event_click){
              event_click.preventDefault();
              window.location.href = <%= banner.link %>;
            });

          });
        </script>
        <li id="slider-<%= banner.id %>-click-action" class="slider-<%= banner.id %>"><div id="descr_no_click"><h3><%= link_to(banner.name, banner.link) %></h3><p><%= banner.description.html_safe %></p> <a class="btn" href="<%= banner.link %>">детальней</a> <i></i></div></li>
      <% end %>


      <!--<li class="slider-1"><div><h3>GPS мониторинг</h3><p>разнообразний текст о работе даного отдела</p> <a href="/about-system">детальней</a> <i></i></div></li>-->
      <!--<li class="slider-2"><div><h3>Окупність системи</h3><p>Повна окупність системи за 6 місяців</p> <a href="/about-system">детальней</a> <i></i></div></li>-->
      <!--<li class="slider-3"><div><h3>Можливість контролю рухомих обєктів з</h3><p>Компьютера <br/> Планшета <br/>e Мобільного телефону</p> <a href="/about-system">детальней</a> <i></i></div></li>-->
    </ul>
  </article>



</header>

app/views/partials/_header_no_index.html.erb
<header style="position: relative;top: -5px;">
	<section id="inf-nav">
		<nav>
			<ul>
        <!-- TODO: add actionname and conroller names for article and newws item -->
				<li<% if controller_name == 'page' && action_name == 'about_us' %> class="active_top_menu" <% else %> <% end %>><%= link_to 'о компании', about_us_path %></li>
				<li<% if (controller_name == 'publication' && action_name == 'news_index') || (controller_name == 'publication' && action_name == 'news_show') %> class="active_top_menu" <% else %> <% end %>><%= link_to 'новости', news_index_path %></li>
				<li<% if (controller_name == 'publication' && action_name == 'articles_index') || (controller_name == 'publication' && action_name == 'articles_show') %> class="active_top_menu" <% else %> <% end %>><%= link_to 'статьи', articles_index_path %></li>
        <!--<li><a href="">Еще пункт</a></li>-->
			</ul>
		</nav>
	</section>
	<nav id="main-navigation">
		<ul>
			<li id="logo">
				<%= link_to_unless current_page?(controller: 'page', action: 'index') || current_page?('/'), image_tag('logo.png', :alt => ' '), root_path %>
			</li>
			<li <% if controller_name == "page" && action_name == "about_system" %> class="active_item" <% end %>>
        <% if controller_name == "page" && action_name == "about_system" %>
        <a>
          <i>возможности</i>
          <b>системы</b>
        </a>
        <% else %>
        <%= link_to about_system_path do %>
            <i>возможности</i>
            <b>системы</b>
        <% end %>
        <% end %>
      </li>
			<li <% if (controller_name == 'publication' && action_name == 'usage_index') || (controller_name == 'publication' && action_name == 'usage_show') %> class="active_item" <% end %> >
        <%
          if (controller_name == 'publication' && action_name == 'usage_index') #||
              #(controller_name == 'publication' && action_name == 'usage_show')
        %>
          <a>
            <i>области</i>
            <b>применения</b>
          </a>
        <% else %>
          <%= link_to usage_index_path do %>
            <i>области</i>
            <b>применения</b>
          <% end %>
        <% end %>
			</li>
			<li id="eq-li"
      <%
        if (controller_name == 'product' && action_name == 'index') ||
            (controller_name == 'product' && action_name == 'by_type') ||
            (controller_name == 'product' && action_name == 'by_brand') ||
            (controller_name == 'product' && action_name == 'by_id') ||
            (controller_name == 'product' && action_name == 'show')
      %>
      class="active_item"
      <% end %>
      >
        <a id="equipment_nav">
				  <i>необходимое</i>
				  <b>оборудование</b>
			  </a>
          <ol id="sub_nav_main">
            <li class="gps_li"> <i class="gps_m"></i> <%= link_to 'GPS трекеры', product_by_type_path(:product_type_id => 'gps-trekery') %><hr/></li>
            <li class="add_li"> <i class="add_m"></i> <%= link_to 'Дополнительное оборудование', product_by_type_path(:product_type_id => 'dopolnitelnoe-oborudovanie') %><hr/></li>
            <li class="controll_li"> <i class="controll_m"></i> <%= link_to 'Контроль топлива', product_by_type_path(:product_type_id => 'kontrol-topliva') %><hr/></li>
          </ol>
      </li>
			<li <% if controller_name == 'page' && action_name == 'economy_effect' %> class="active_item" <% end %> >
        <% if controller_name == 'page' && action_name == 'economy_effect' %>
        <a>
				  <i>экономический</i>
				  <b>эффект</b>
			  </a>
        <% else %>
        <%= link_to economy_effect_path do %>
            <i>экономический</i>
            <b>эффект</b>
        <% end %>
        <% end %>
      </li>
			<li <% if (controller_name == 'contact' && action_name == 'new') || (controller_name == 'contact' && action_name == 'create') %> class="active_item" <% end %>>
        <% if (controller_name == 'contact' && action_name == 'new') || (controller_name == 'contact' && action_name == 'create') %>
        <a>
				  <i>наши</i>
				  <b>контакты</b>
			  </a>
        <% else %>
          <%= link_to contact_path do %>
            <i>наши</i>
            <b>контакты</b>
          <% end %>
        <% end %>
      </li>

		</ul>
	</nav>

	<div class="item_holder">
		<div id="section-name">
      <% if (controller_name == "publication" && action_name == "usage_show") || (controller_name == "publication" && action_name == "news_show") || (controller_name == "publication" && action_name == "articles_show.html.erb") %>
        <h2><%= @page_title %></h2>
        <% else %>
        <h1><%= @page_title %></h1>
      <% end %>
		</div>
	</div>


</header>

<%= render :partial => 'partials/bread' %>