config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'

  scope '(:locale)', :locale => /ru|uk/ do

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    # Faq
    get 'faq', to: 'faq#index', as: 'faq_index'
    get 'faq/:id', to: 'faq#show', as: 'faq_item'

    # System usage index and show pages
    get 'usage', to: 'publication#usage_index', as: 'usage_index'
    get 'usage/:id', to: 'publication#usage_show', as: 'usage_show'

    # News index and show pages
    get 'news', to: 'publication#news_index', as: 'news_index'
    get 'news/:id', to: 'publication#news_show', as: 'news_show'

    # Articles index and show pages
    get 'articles', to: 'publication#articles_index', as: 'articles_index'
    get 'articles/:id', to: 'publication#articles_show', as: 'articles_show'

    # Work out for products
    get 'equipments', to: 'product#index', as: 'product_index'
    get 'equipments/:product_type_id', to: 'product#by_type', as: 'product_by_type'
    get 'equipments/:product_type_id/:product_brand_id', to: 'product#by_brand', as: 'product_by_brand'
    get 'equipments/:product_type_id/:product_brand_id/:id', to: 'product#by_id', as: 'product_by_id'


    # Static pages
    get 'terms', to: 'page#terms', as: 'terms'
    get 'about-system', to: 'page#about_system', as: 'about_system'
    get 'about-us', to: 'page#about_us', as: 'about_us'
    get 'economy-effect', to: 'page#economy_effect', as: 'economy_effect'
    get 'page-not-found', to: 'page#error_404', as: 'page_not_found'
    get 'sitemap', to: 'page#sitemap', as: 'sitemap'

    get 'condition', to: 'page#condition', as: 'condition'

    get 'contact-us', to: 'contact#new', as: 'contact'
    get 'call-back', to: 'contact#feedback', as: 'feedback'
    #post 'contact-us', to: 'contact#create', as: 'contact'
    #resource :contacts, only: [:new, :create]
    #match 'contact-us' => 'contact#new', :as => 'contact', :via => :get
    #match 'contact-us' => 'contact#create', :as => 'contact', :via => :post

    # Root patch
    root 'page#index'

  end

end

app/views/page/about_system.html.erb
<% content_for :meta_head do %>
  <meta name="description" content="<%= get_static(30).meta_description %>"/>
  <meta name="keywords" content="<%= get_static(30).meta_keywoard %>"/>
<% end %>
<!--noindex-->
<style>
  header{
    background-image: url("<%= image_path('banners/na-web-other-banners-10.jpg') %>") !important;
  }
</style>
<!--/noindex-->

<section id="section">
  <article class="system_ability clearfix">
    <%= get_static(30).full_description.html_safe %>
  </article>
</section>

app/views/page/about_us.html.erb
<% content_for :meta_head do %>
  <meta name="description" content="<%= get_static(28).meta_description %>"/>
  <meta name="keywords" content="<%= get_static(28).meta_keywoard %>"/>
<% end %>
<!--noindex-->
<style>
  header{
    background-image: url("<%= image_path('banners/na-web-other-banners-5.jpg') %>") !important;
  }
</style>
<!--/noindex-->

<section id="section">
  <article class="about_us clearfix">
    <%= get_static(28).full_description.html_safe %>
  </article>
</section>

app/views/page/condition.html.erb
<!--noindex-->
<style>
  header{
    background-image: url("<%= image_path('banners/na-web-other-banners-5.jpg') %>") !important;
  }
</style>
<!--/noindex-->

<section id="section">

</section>

app/views/page/economy_effect.html.erb
<% content_for :meta_head do %>
  <meta name="description" content="<%= get_static(29).meta_description %>"/>
  <meta name="keywords" content="<%= get_static(29).meta_keywoard %>"/>
<% end %>
<!--noindex-->
<style>
  header{
    background-image: url("<%= image_path('banners/na-web-other-banners-3.jpg') %>") !important;
  }
</style>
<!--/noindex-->
<section id="section">
  <article class="economy_effect clearfix">
    <%= get_static(29).full_description.html_safe %>
  </article>
</section>

app/views/page/index.html.erb
<section id="page" role="content">
  <article id="main__intro_page">
    <div class="holder_item">
      <%= get_static(2).full_description.html_safe %>
    </div>
  </article>
  <!-- main__intro_page -->

  <article id="main__info_slider_page">
    <div class="holder_item" >

      <div class="hl-slides" id="main_index_page_slider_content">
        <div class="slide-index-1 slide-index">
          <div class="ll">
            <div class="hl">
              <h3>Возможности системы GPS МОНИТОРИНГА</h3>
              <p>Система способна выдавать комплексную информацию относительно:</p>
            </div>

            <%= image_tag('static/slide-index-page-1.jpg') %>
          </div>
          <div class="rr">
            <ul class="dash_o">
              <li>Местонахождение объекта (остановки /стоянки)</li>
              <li>Маршрута транспортного средства и его соответствие составленному плану</li>
              <li>Скорости и время движения</li>
              <li>Количество топлива в баках и каких-либо ее изменений</li>
              <li>Загруженности подвижных средств</li>
              <li>Технических характеристик функционирования автотранспорта</li>
              <li>Использование систем автомобиля в том числе открывания/закрывания дверей</li>
              <li>Событий в салоне транспортных средств</li>
              <li>Обращение водителя до кнопки тревоги и др.</li>
            </ul>
            <span class="_tri"></span><%= link_to 'Узнать подробности', about_system_path %>
          </div>
        </div><!-- slide -->

        <div class="slide-index-2 slide-index">
          <div class="ll">
            <div class="hl">
              <h3>Схема работы GPS МОНИТОРИНГА</h3>
            </div>

          </div>
          <div class="rr">
            <p>Система слежения за подвижными объектами, функционирует на основе технологий GPS, ГЛОНАСС, GSM, GPRS и EDGE. Функциями системы является мониторинг деятельности подвижных объектов и диспетчеризация автотранспорта.</p>
            <span class="_tri"></span><%= link_to 'Узнать подробности', about_system_path %>
          </div>
        </div><!-- slide -->


        <div class="slide-index-3 slide-index">
          <div class="ll">
            <div class="hl">
              <h3>Экономический эффект внедрения GPS МОНИТОРИНГА</h3>
            </div>

            <%= image_tag('static/slide-index-page-3.jpg') %>
          </div>
          <div class="rr">
            <p>Уменьшение себестоимости производства и мобилизация всех имеющихся ресурсов предприятия - современные требования, что их ставят экономические реалии перед бизнес-структурами самой разнообразной специализации.</p>
            <p>Именно на составляющую экономии и рациональное использование транспортного парка на основе новейших технологий были направлены усилия разработчиков системы GPS-мониторинга.</p>
            <span class="_tri"></span><%= link_to 'Узнать подробности', economy_effect_path %>
          </div>
        </div><!-- slide -->
      </div>




    </div>
  </article>
  <!-- main__info_slider -->

  <article id="main__intro_system_usage_page">
    <div class="holder_item">
      <h2><%= t('system_elements.unsorted.usage_header') %></h2>
      <% @system_usage_home.publications.last(6).each do |item| %>
          <div class="_system_usage_item">
            <%= image_tag item.avatar.url(:usage_avatar) %>
            <h3><%= link_to item.name, usage_show_path(:id => item.slug, :publication_catalog_id => 4) %></h3>
            <p><%= item.short_description %></p>
          </div>
      <% end %>
      <div class="_all_system_links">
        <span class="_tri"></span> <%= link_to(t('system_elements.unsorted.usage_link'), usage_index_path(:publication_catalog_id => 4)) %>
      </div>
    </div>
    <!-- holder item with system usage elements -->
  </article>
  <!-- main__intro_system_usage -->
  <article class="system_try_out">
    <div class="holder__i">
      <div class="ll">
        <p>Опробуйте систему
          в демо действии</p>
        <p>!</p>
      </div>
      <div class="rr">
        <form action="http://nautica.com.ua/ru/">
          <script type="text/javascript" charset="utf-8">
            $(document).on('ready page:load', function () {
               $(".user_i").click(function(){
                 $("#login").val('demogps');
               });

              $(".pass_i").click(function(){
                $("#password").val('bestnav');
              });
            });
          </script>
          <div class="field first">
            <input class="" type="text" id="login" name="login" placeholder="demogps"/>
            <label for="login">пользователь: <i class="user_i">demogps</i></label>
          </div>
          <div class="field middle">
            <input type="password" id="password" name="password" placeholder="*******"/>
            <label for="password">пароль: <i class="pass_i">bestnav</i></label>
          </div>
          <div class="field last">
            <button type="submit">Войти</button>
          </div>
        </form>
      </div>
    </div>
  </article>
  <article id="why__we_are__landing">
    <div class="holder_item">
      <%= get_static(3).full_description.html_safe %>
    </div>
  </article>

  <article id="_latest_new_publications">
    <div class="holder_item">
      <div class="section__l_news">
        <h2><%= link_to t('system_elements.unsorted.news_header'), news_index_path(:publication_catalog_id => 2) %></h2>
        <% @news_home.publications.limit(4).each do |item| %>
            <div class="__l_news_item">
              <%= link_to(image_tag(item.avatar.url(:news_avatar)), news_show_path(:id => item.slug, :publication_catalog_id => 2)) %>
              <h3><%= link_to item.name, news_show_path(:id => item.slug, :publication_catalog_id => 2) %></h3>
              <i><%= item.created_at.strftime("%d.%m.%Y") %></i>
              <p><%= item.short_description %></p>
            </div>
        <% end %>
      </div>
      <div class="section__r_publication">
        <h2><%= link_to t('system_elements.unsorted.articles_header'), articles_index_path(:publication_catalog_id => 1) %></h2>
        <% @article_home.publications.each do |item| %>
            <div class="__r_publication_item">
              <h3><%= link_to item.name, articles_show_path(:id => item.slug, :publication_catalog_id => 1) %></h3>
              <%= link_to(image_tag(item.avatar.url(:article_avatar)), articles_show_path(:id => item.slug, :publication_catalog_id => 1)) %>
              <p><%= item.short_description %></p>
            </div>
        <% end %>
      </div>
    </div>
  </article>
</section> <!-- #page -->

app/views/page/sitemap.html.erb
<section id="section">

</section>

app/views/page/terms.html.erb
<section id="section">
	<div class="item_holder">
		<h1><%= @page_title %></h1>
		<%= get_static(22).full_description.html_safe %>
	</div>
</section>