config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'

  scope '(:locale)', :locale => /ru|uk/ do

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    # Faq
    get 'faq', to: 'faq#index', as: 'faq_index'
    get 'faq/:id', to: 'faq#show', as: 'faq_item'

    # System usage index and show pages
    get 'usage', to: 'publication#usage_index', as: 'usage_index'
    get 'usage/:id', to: 'publication#usage_show', as: 'usage_show'

    # News index and show pages
    get 'news', to: 'publication#news_index', as: 'news_index'
    get 'news/:id', to: 'publication#news_show', as: 'news_show'

    # Articles index and show pages
    get 'articles', to: 'publication#articles_index', as: 'articles_index'
    get 'articles/:id', to: 'publication#articles_show', as: 'articles_show'

    # Work out for products
    get 'equipments', to: 'product#index', as: 'product_index'
    get 'equipments/:product_type_id', to: 'product#by_type', as: 'product_by_type'
    get 'equipments/:product_type_id/:product_brand_id', to: 'product#by_brand', as: 'product_by_brand'
    get 'equipments/:product_type_id/:product_brand_id/:id', to: 'product#by_id', as: 'product_by_id'


    # Static pages
    get 'terms', to: 'page#terms', as: 'terms'
    get 'about-system', to: 'page#about_system', as: 'about_system'
    get 'about-us', to: 'page#about_us', as: 'about_us'
    get 'economy-effect', to: 'page#economy_effect', as: 'economy_effect'
    get 'page-not-found', to: 'page#error_404', as: 'page_not_found'
    get 'sitemap', to: 'page#sitemap', as: 'sitemap'

    get 'condition', to: 'page#condition', as: 'condition'

    get 'contact-us', to: 'contact#new', as: 'contact'
    get 'call-back', to: 'contact#feedback', as: 'feedback'
    #post 'contact-us', to: 'contact#create', as: 'contact'
    #resource :contacts, only: [:new, :create]
    #match 'contact-us' => 'contact#new', :as => 'contact', :via => :get
    #match 'contact-us' => 'contact#create', :as => 'contact', :via => :post

    # Root patch
    root 'page#index'

  end

end

app/models/catalog/product.rb
class Catalog::Product < ActiveRecord::Base
  attr_accessible :name, :header, :short_description, :full_description, :slug, :product_brand_id, :product_brand, :tech_spec, :interface_spec, :feature_spec, :additional_spec, :translations, :translations_attributes, :avatar
  belongs_to :product_brand
  before_validation :generate_uri
  default_scope { order('created_at DESC') }

  has_one :static_page_data, :as => :has_static_page_data
  accepts_nested_attributes_for :static_page_data, :allow_destroy => true

  translates :name, :header, :short_description, :full_description, :tech_spec, :interface_spec, :feature_spec, :additional_spec, :fallbacks_for_empty_translations => true

  class Translation
    attr_accessible :locale, :name, :header, :short_description, :full_description, :tech_spec, :interface_spec, :feature_spec, :additional_spec, :product_brand_id, :product_brand
    rails_admin do
      visible false
      nested do
        field :locale, :hidden
        field :name do
          label 'Название'
          help ''
        end
        field :header do
          label 'Заголовок'
          help ''
        end
        field :short_description do
          label 'Краткое описание'
          help ''
        end
        field :full_description, :ck_editor do
          label 'Содержание'
          help ''
        end
        field :tech_spec, :ck_editor do
          label 'Технические спецификации'
          help ''
        end
        field :interface_spec, :ck_editor do
          label ''
          help ''
        end
        field :feature_spec, :ck_editor do
          label ''
          help ''
        end
        field :additional_spec, :ck_editor do
          label ''
          help ''
        end
      end
    end
  end

  accepts_nested_attributes_for :translations
  validates :name, presence: true, allow_blank: false
  validates :header, presence: true, allow_blank: false
  validates :short_description, presence: true, allow_blank: false
  validates :slug, presence: true, allow_blank: false, uniqueness: true
  validates :product_brand, presence: true

  has_attached_file :avatar, styles:{
      main: '265x180^'
  },
                    url:'/assets/images/equipment/:class/:id/image_:style.:extension',
                    path:':rails_root/public:url'

  validates_attachment :avatar, content_type: { content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif'] }

  def to_param
    slug
  end

  def generate_uri
    self.slug = name.parameterize
  end

  rails_admin do
    list do
      field :avatar
      field :name
      field :product_brand
    end
    edit do
      field :avatar, :paperclip
      field :product_brand do
        inline_add false
        inline_edit false
      end
      field :name
      field :slug do
        visible false
      end
      field :header
      field :short_description
      field :full_description, :ck_editor
      field :tech_spec, :ck_editor
      field :interface_spec, :ck_editor
      field :feature_spec, :ck_editor
      field :additional_spec, :ck_editor
      field :translations, :globalize_tabs
      field :static_page_data
    end
  end
end

app/models/catalog/product_type.rb
class Catalog::ProductType < ActiveRecord::Base
  #set_table_name "product_types"
  # Model fields
  attr_accessible :name, :slug, :product_brands, :translations, :translations_attributes
  # Model relations
  has_many :product_brands
  # Defualt sorting from database
  default_scope {order('created_at DESC')}
  # Validation details
  validates :name, presence: true, allow_blank: false
  validates :slug, presence: true, uniqueness: true
  # Before validates
  before_validation :friendly_url
  # Translate
  translates :name, :fallbacks_for_empty_translations => true
  # Translates class
  class Translation
    attr_accessible :locale, :product_type_id, :name

    rails_admin do
      label 'Перевод'
      label_plural 'Перевод'
      visible false
      nested do
        field :locale, :hidden
        field :name do
          label 'Название'
        end
      end
    end
  end
  # Nested for translates
  accepts_nested_attributes_for :translations
  # Generate url
  def to_param
    slug
  end

  def friendly_url
    self.slug = name.parameterize
  end

  rails_admin do
    list do
      field :name
    end
    edit do
      field :name
      field :slug#, :hidden
      field :translations, :globalize_tabs
    end
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController

  add_breadcrumb " ", :root_path

  def index
    if params[:search]
      @products = Catalog::Product.where("name like ?", "%#{params[:search]}%").paginate(:page => params[:page], :per_page => 9)

      @page_title = I18n.t('system_elements.unsorted.search')
      add_breadcrumb @page_title

      if @products.empty?
        render template: "product/empty_search"
      end

      add_breadcrumb params[:search]
    else
      @products = Catalog::Product.paginate(:page => params[:page])
      @page_title = I18n.t('system_elements.breadcrumbs.equipment')
      add_breadcrumb @page_title
      render template: "product/catalog"
    end
  end

  def show
  end

  def by_type
    @products_type ||= Catalog::ProductType.find_by_slug!(params[:product_type_id])
    @products = @products_type
    @page_title = @products_type.name
    add_breadcrumb I18n.t('system_elements.breadcrumbs.equipment'), :product_index_path
    add_breadcrumb @products_type.name
  end

  def by_brand
    @products_brand ||= Catalog::ProductBrand.find_by_slug!(params[:product_brand_id])
    @all_brands = Catalog::ProductBrand.where("product_type_id like ? ", "%#{@products_brand.product_type.id}%")
    @products = @products_brand
    @page_title = @products_brand.name
    #add_breadcrumb I18n.t('system_elements.breadcrumbs.equipment'), :product_index_path
    add_breadcrumb @products_brand.product_type.name, product_by_type_path(:product_type_id => @products_brand.product_type.slug)
    add_breadcrumb @products_brand.name
  end

  def by_id
    @product ||= Catalog::Product.find_by_slug!(params[:id])
    @page_title = @product.name
    #add_breadcrumb I18n.t('system_elements.breadcrumbs.equipment'), :product_index_path
    add_breadcrumb @product.product_brand.product_type.name, product_by_type_path(:product_type_id => @product.product_brand.product_type.slug)
    add_breadcrumb @product.product_brand.name, product_by_brand_path(:product_brand_id => @product.product_brand.slug)
    add_breadcrumb @page_title
  end



end

app/helpers/product_helper.rb
module ProductHelper
end

app/views/product/by_brand.html.erb
<!--noindex-->
<style>
  header {
    background-image: url("<%= image_path('banners/na-web-other-banners-2.jpg') %>") !important;
  }
</style>
<!--/noindex-->

<section id="section">
  <article class="product_by_type clearfix product_by_brand_page">

    <nav id="sorting-by-brand">
      <form action="/product">
        <select name="product_brand" id="select-beast-empty">
          <!--<option value="Все">Все</option>-->
          <% @all_brands.each do |sort| %>
            <option value="<%= sort.slug %>"><%= sort.name %><%#= link_to sort.name, product_by_brand_path(:product_brand_id => sort.slug, :product_type_id => sort.product_type.slug) %></option>
          <% end %>
        </select>
      </form>
    </nav>

    <% @products.products.each do |item| %>
      <article class="product_item">
        <h3><%= item.name %></h3>
        <%= image_tag item.avatar.url(:main), alt: item.name %>
        <p><%= item.short_description %></p>
        <%= link_to  product_by_id_path(:id => item.slug, :product_type_id => item.product_brand.product_type.slug, :product_brand_id => item.product_brand.slug) do %>
          <i></i> подробное описание
          <% end %>
      </article>
    <% end %>

  </article>
</section>

app/views/product/by_id.html.erb
<!--noindex-->
<style>
  header{
    background-image: url("<%= image_path('banners/na-web-other-banners-2.jpg') %>") !important;
  }
</style>
<!--/noindex-->

<%#= @product.inspect %>

<section id="product_by_id" class="clearfix">
  <article class="holder_product">
    <h2 class="product_headline"><%= @product.header %></h2>
    <article class="pr-main-holder clearfix">
      <div class="ll">
        <%= image_tag(@product.avatar.url(:main), alt: @product.name) %>
      </div>

      <div class="rr">
        <%= raw @product.full_description %>
      </div>
    </article>
    <article class="product_features clearfix">
      <div id="product_features_tabs">
        <%= link_to "Технические характеристики", '', id: "#tab1", class: 'active_tab_selected', data: { 'tabs' => 'tab1-c' }  %>
        <%= link_to "Интерфейсы", '', id: "#tab2", data: { 'tabs' => 'tab2-c' } %>
        <%= link_to "Особенности", '', id: "#tab3", data: { 'tabs' => 'tab3-c' } %>
        <%= link_to "Дополнительное оборудование", '', id: "#tab4", data: { 'tabs' => 'tab4-c' } %>
      </div>
      <div id="product_features_tabs_content">
        <div class="tab-content tab1_content clearfix" id="tab1-c">
          <%= raw @product.tech_spec %>
        </div>
        <div class="tab-content tab2_content clearfix" id="tab2-c">
          <%= raw @product.interface_spec %>
        </div>
        <div class="tab-content tab3_content clearfix" id="tab3-c">
          <%= raw @product.feature_spec %>
        </div>
        <div class=" tab-content tab4_content clearfix" id="tab4-c">
          <%= raw @product.additional_spec %>
        </div>
      </div>
    </article>
  </article>
</section>

app/views/product/by_type.html.erb
<!--noindex-->
<style>
  header{
    background-image: url("<%= image_path('banners/na-web-other-banners-2.jpg') %>") !important;
  }
</style>
<!--/noindex-->

<section id="section">
  <article class="product_by_type clearfix">





    <nav id="sorting-by-brand">
      <form action="/product">
        <select name="product_brand" id="select-beast-empty">
          <!--<option value="Все">Все</option>-->
          <% @products.product_brands.each do |sort| %>

            <option value="<%= sort.slug %>"><%= sort.name %><%#= link_to sort.name, product_by_brand_path(:product_brand_id => sort.slug, :product_type_id => sort.product_type.slug) %></option>
          <% end %>
        </select>
      </form>

      <!-- ul -->



        <!-- li><%#= link_to_unless @products.blank?, "Все", product_by_type_path(:product_type_id => @products_type.slug) %></li>
        <%# @products.product_brands.each do |sort| %>
          <li><%#= link_to sort.name, product_by_brand_path(:product_brand_id => sort.slug, :product_type_id => sort.product_type.slug) %></li>
        <%# end %>
      </ul -->
    </nav>

    <% @products.product_brands.each do |brand| %>
      <% brand.products.each do |item| %>
        <article class="product_item">
          <h3><%= link_to(item.name, product_by_id_path(:id => item.slug, :product_type_id => item.product_brand.product_type.slug, :product_brand_id => item.product_brand_id)) %></h3>
          <%= link_to(image_tag(item.avatar.url(:main), alt: item.name), product_by_id_path(:id => item.slug, :product_type_id => @products_type.slug, :product_brand_id => brand.slug)) %>
          <p><%= item.short_description %></p>
          <%= link_to  product_by_id_path(:id => item.slug, :product_type_id => @products_type.slug, :product_brand_id => brand.slug), class: 'button' do %>
            <i></i> подробное описание
          <% end %>
        </article>
      <% end %>
    <% end %>
  </article>
</section>

app/views/product/catalog.html.erb
<section id="product-catalog" class="clearfix">

  <article>
    <%= link_to(image_tag("icons/gps-menu.svg", alt: ""), product_by_type_path(:product_type_id => 'gps-trekery')) %>
    <h2><%= link_to t('system_elements.footer.menu.gps_menu'), product_by_type_path(:product_type_id => 'gps-trekery') %></h2>
    <p>Служба Яндекс.Рефераты предназначена для студентов и школьников, дизайнеров и журналистов, создателей научных заявок и отчетов — для всех, создателей научных</p>
  </article>

  <article>
    <%= link_to(image_tag("icons/aditional-menu.svg", alt: ""), product_by_type_path(:product_type_id => 'dopolnitelnoe-oborudovanie')) %>
    <h2><%= link_to t('system_elements.footer.menu.additional_menu'), product_by_type_path(:product_type_id => 'dopolnitelnoe-oborudovanie') %></h2>
    <p>Служба Яндекс.Рефераты предназначена для студентов и школьников, дизайнеров и журналистов, создателей научных заявок и отчетов — для всех, создателей научных</p>
  </article>

  <article>
    <%= link_to(image_tag("icons/controll-menu.svg", alt: ""), product_by_type_path(:product_type_id => 'kontrol-topliva')) %>
    <h2><%= link_to t('system_elements.footer.menu.controll_menu'), product_by_type_path(:product_type_id => 'kontrol-topliva') %></h2>
    <p>Служба Яндекс.Рефераты предназначена для студентов и школьников, дизайнеров и журналистов, создателей научных заявок и отчетов — для всех, создателей научных</p>
  </article>

</section>

app/views/product/empty_search.html.erb
<!--noindex-->
<style>
  header{
    background-image: url("<%= image_path('banners/na-web-other-banners-2.jpg') %>") !important;
  }
</style>
<!--/noindex-->
<section id="empty_search">
  <h2>По вашему запросу ничего не найденно!</h2>

  <div class="search-me">
    <%= form_tag(product_index_path, :method => "get", id: "header_search", class: 'search') do %>
      <%= text_field_tag :search, params[:search], placeholder: "", id: 'search_field' %>
      <label for="search_field">Например: <a href="#gps">GPS</a></label>
    <% end %>

    <a class="button" id="open-seacrh"><%= image_tag('icons/search.svg') %></a>

  </div>
</section>

app/views/product/index.html.erb
<!--noindex-->
<style>
  header{
    background-image: url("<%= image_path('banners/na-web-other-banners-2.jpg') %>") !important;
  }
</style>
<!--/noindex-->

<section id="section">
  <article class="product_by_type clearfix">
    <nav>
      <ul>
        <li><a href=""></a></li>
      </ul>
    </nav>
    <% @products.each do |item| %>
      <article class="product_item">
        <h3><%= link_to(item.name, product_by_id_path(:id => item.slug, :product_type_id => item.product_brand.product_type.slug, :product_brand_id => item.product_brand_id)) %></h3>
        <%= link_to(image_tag(item.avatar.url(:main), alt: item.name), product_by_id_path(:id => item.slug, :product_type_id => item.product_brand.product_type.slug, :product_brand_id => item.product_brand_id)) %>
        <p><%= item.short_description %></p>
        <%= link_to 'подробное описание', product_by_id_path(:id => item.slug, :product_type_id => item.product_brand.product_type.slug, :product_brand_id => item.product_brand_id), class: 'button' %>
      </article>
    <% end %>

    <%= will_paginate @products %>

  </article>

</section>

app/views/product/show.html.erb
<!--noindex-->
<style>
  header{
    background-image: url("<%= image_path('banners/na-web-other-banners-2.jpg') %>") !important;
  }
</style>
<!--/noindex-->