config/routes.rb
Rails.application.routes.draw do


  mount Ckeditor::Engine => '/ckeditor'

  scope '(:locale)', :locale => /ru|uk/ do

    mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

    # Faq
    get 'faq', to: 'faq#index', as: 'faq_index'
    get 'faq/:id', to: 'faq#show', as: 'faq_item'

    # System usage index and show pages
    get 'usage', to: 'publication#usage_index', as: 'usage_index'
    get 'usage/:id', to: 'publication#usage_show', as: 'usage_show'

    # News index and show pages
    get 'news', to: 'publication#news_index', as: 'news_index'
    get 'news/:id', to: 'publication#news_show', as: 'news_show'

    # Articles index and show pages
    get 'articles', to: 'publication#articles_index', as: 'articles_index'
    get 'articles/:id', to: 'publication#articles_show', as: 'articles_show'

    # Work out for products
    get 'equipments', to: 'product#index', as: 'product_index'
    get 'equipments/:product_type_id', to: 'product#by_type', as: 'product_by_type'
    get 'equipments/:product_type_id/:product_brand_id', to: 'product#by_brand', as: 'product_by_brand'
    get 'equipments/:product_type_id/:product_brand_id/:id', to: 'product#by_id', as: 'product_by_id'


    # Static pages
    get 'terms', to: 'page#terms', as: 'terms'
    get 'about-system', to: 'page#about_system', as: 'about_system'
    get 'about-us', to: 'page#about_us', as: 'about_us'
    get 'economy-effect', to: 'page#economy_effect', as: 'economy_effect'
    get 'page-not-found', to: 'page#error_404', as: 'page_not_found'
    get 'sitemap', to: 'page#sitemap', as: 'sitemap'

    get 'condition', to: 'page#condition', as: 'condition'

    get 'contact-us', to: 'contact#new', as: 'contact'
    get 'call-back', to: 'contact#feedback', as: 'feedback'
    #post 'contact-us', to: 'contact#create', as: 'contact'
    #resource :contacts, only: [:new, :create]
    #match 'contact-us' => 'contact#new', :as => 'contact', :via => :get
    #match 'contact-us' => 'contact#create', :as => 'contact', :via => :post

    # Root patch
    root 'page#index'

  end

end

app/views/layouts/application.html.erb
<!doctype html>
<html lang="uk">
<head>
  <meta charset="UTF-8">
  <%= edge_ie %>
  <%= disable_seo %>
  <%= ve_development_tag %>
  <%= csrf_meta_tags %>
  <% if @static_page_data %>
    <title><%= @static_page_data.head_title %></title>
    <meta name="keywords" content="<%= @static_page_data.meta_keywords %>" />
    <meta name="description" content="<%= @static_page_data.meta_description %>" />
  <% else %>

  <% end %>
  <!--[if lt IE 9]>
  <%= javascript_include_tag 'html5shiv.min' %>
  <![endif]-->
	<link rel="stylesheet" href="//code.cdn.mozilla.net/fonts/fira.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://maps.googleapis.com/maps/api/js?sensor=false' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


</head>

<body data-smoothscrolling="true" <% if (controller_name == 'contact' && action_name == 'new') || (controller_name == 'contact' && action_name == 'create') %> onload="initializeGMaps()" onloadeddata="initializeGMaps()" onloadstart="initializeGMaps()" <% end %>>

<section id="magic-wrapper">

<section id="sub-navigation">
  <div class="sub_holder_wrapper">

    <div class="ll">
      <form action="" class="login" id="header_login">
        <script type="text/javascript" charset="utf-8">
          $(document).on('ready page:load', function () {
            $("#user_i").click(function(){
              $("#login_t").val('demogps');
            });

            $("#pass_i").click(function(){
              $("#password_t").val('bestnav');
            });
          });
        </script>
        <div class="field first">
          <input class="" type="text" id="login_t" name="login" placeholder="demogps"/>
          <label for="login">пользователь: <i class="user_i" id="uses_i">demogps</i></label>
        </div>
        <div class="field middle">
          <input type="password" id="password_t" name="password" placeholder="*******"/>
          <label for="password">пароль: <i class="pass_i" id="pass_i">bestnav</i></label>
        </div>
      </form>
      <%= form_tag(product_index_path, :method => "get", id: "header_search", class: 'search') do %>
        <%= text_field_tag :search, params[:search], placeholder: "", id: 'search_field' %>
        <label for="search_field">Например: <a href="#gps">GPS</a></label>
      <% end %>

      <a class="button text" id="open-login">Войти</a>
      <a class="button" id="open-seacrh"><%= image_tag('icons/search.svg') %></a>
    </div>

    <div class="mm">
      <p>+38 <span>(</span>067<span>)</span> 340-26-13</p>
      <p>+38 <span>(</span>032<span>)</span> 295-72-96</p>
      <a href="/call-back" id="call-back-btn" data-fancybox-type="iframe">заказать обратный звонок</a>
    </div>

    <div class="rr">
      <p><%= link_to_unless I18n.locale == :ru, "RUS", locale: :ru %></p>
      <p><%= link_to_unless I18n.locale == :uk, "UA", locale: :uk %></p>
    </div>


  </div>
</section>
<section class="nav_act">
  <span class="trio"></span>
  <%= link_to(image_tag('icons/second-nav.svg', width: 18, height: 18, class: 'rotate'), '', id: 'navigation-menu') %>
</section>
	<% if current_page?(controller: 'page', action: 'index') || current_page?('/') %>
		<%= render :partial => 'partials/header_index' %>
	<% else %>
		<%= render :partial => 'partials/header_no_index' %>
	<% end %>
	<%= yield %>
<section id="__to__top">
	<div class="__hold_me">
		<div class="trio"></div>
	</div>
</section>
</section>
<footer>
	<section id="__ff_menu">
		<article id="bottom-nav">
			<nav>
				<ul>
					<li><span class="_tri"></span><%= link_to t('system_elements.footer.menu.abouts_us'), about_us_path %></li>
					<li><span class="_tri"></span><%= link_to t('system_elements.footer.menu.ability'), about_system_path %></li>
					<li><span class="_tri"></span><%= link_to t('system_elements.footer.menu.equipment'), product_index_path %></li>
					<li><span class="_tri"></span><%= link_to t('system_elements.footer.menu.ecoeffect'), economy_effect_path %></li>
					<li><span class="_tri"></span><%= link_to t('system_elements.footer.menu.faq'), faq_index_path %></li>
					<li><span class="_tri"></span><%= link_to t('system_elements.footer.menu.publication'), articles_index_path(:publication_catalog_id => 1) %></li>
					<li><span class="_tri"></span><%= link_to t('system_elements.footer.menu.news'), news_index_path(:publication_catalog_id => 2) %></li>
					<li><span class="_tri"></span><%= link_to t('system_elements.footer.menu.contact'), contact_path %></li>
				</ul>
			</nav>
		</article>
		<article class="_footer_contact">
			<p>+38 <span>(</span>067<span>)</span> 340-26-13</p>
			<p>+38 <span>(</span>032<span>)</span> 295-72-96</p>
			<div>
				<%= image_tag 'icons/map-ico.png' %>
				<p>
					вул. Щирецька, 36, оф. 205, <br/>
					м.Львів, Україна
				</p>
			</div>
		</article>
	</section>
	<section id="__ff_copy__studio">
		<p>© 2009-2014 ТзОВ «Наутіка»  Всі права застережено. </p>
	</section>
	<article id="__ff_line"></article>
	<section id="_bottom_line_END">
    <div id="_f_section">
      <div class="studio">
        <%= image_tag 'studio-logo.svg', width: 50, height: 52, alt: 'Розроблено в студії  М. Вороніна в 2014 році.' %>
        <p>Розроблено в <%= link_to 'студії М. Вороніна', 'http://voroninstudio.eu', target: '_blank' %> в 2014 році.</p>
      </div>
      <div class="link_menu">
        <%= link_to 'Відповідальність сторін', condition_path %>
        <%= link_to 'Правила користування', terms_path %>
      </div>
      <div class="map_site">
        <%= link_to 'Карта сайту', sitemap_path %>
      </div>
    </div>

	</section>
	<section id="__bottom_line_END">

	</section>
</footer>
<!-- Google Analitics and Google Tags -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-54380249-1', 'auto');
  ga('send', 'pageview');

</script>
<!-- End of Google Analitics and Google Tags -->
</body>
</html>

app/views/layouts/call_back_layouts.html.erb
<!doctype html>
<html lang="uk" style="min-width: 860px !important;">
<head>
  <meta charset="UTF-8">
  <title>Форма обратной связи - "Наутика"</title>
  <!--[if lt IE 9]>
  <%= javascript_include_tag 'html5shiv.min' %>
  <![endif]-->
  <link rel="stylesheet" href="//code.cdn.mozilla.net/fonts/fira.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= ve_development_tag %>
  <%= csrf_meta_tags %>
</head>
<body style="min-width: 860px !important;">
<%= yield %>
</body>
</html>